### ISSUE TITLE
Specify Config Path

### ISSUE THREAD

**Issue by asummers** [karolsluszniak/ex_check#16]
Would you be open to the addition of an opt where you can specify the config path, e.g. 

```
mix check --config ~/my/path/to/config
```

taking precedent over any dir local or home dir configs?

**Comment by karolsluszniak** [comment]
Sure, sounds useful. Feel free to open a pull request.

Btw, out of curioisity, what’s your case for needing it?

**Comment by asummers** [comment]
I centralize my `credo`, etc. config for use in multiple repos, and while in CI I can `cp` it to the relevant place, being able to specify a config path like you can in `credo` is useful. 

```
cd code
mix check --config ../some-ci-repo/conf/.check.exs
```

sort of thing
