### ISSUE TITLE
Check for unused dependencies

### ISSUE THREAD

**Issue by bitboxer** [karolsluszniak/ex_check#35]
Maybe this is a nice addition to the list of things `ex_check` is checking:

```
mix deps.unlock --check-unused
```

This checks if the "mix.lock" file has unused dependencies.

**Comment by bitboxer** [comment]
Ah sorry, somehow I missed this :(

**Comment by karolsluszniak** [comment]
No worries, it reminded me to attend to the repo at just the right time as I struggled to find time in last few weeks and tests on master need to finally get fixed.
