### ISSUE TITLE
halt_exit_status is no longer a valid CLI argument.

### ISSUE THREAD

**Issue by mrz** [karolsluszniak/ex_check#8]
The above warning is displayed when running `mix check`. The `--halt-exit-status` option that is passed [here](https://github.com/karolsluszniak/ex_check/blob/db4f20ec5461be99a8e88eb6bea27e36a0e6eaeb/lib/ex_check/config/default.ex#L13) has been deprecated in [this](https://github.com/jeremyjh/dialyxir/pull/320) pull request. Assuming the user is running at least `dialyxir` 1.0.0-rc7, released September 2019, the warning will be shown. It's easy to fix this by overriding the tool definition in the project `.check.exs` file, but it would be nice to have the correct up-to-date behaviour by default.

**Comment by karolsluszniak** [comment]
I see that we have dialyxir 1.0.0 for 3 months already so it's probably safe to remove this option without extra notes in docs (except for changelog).

Done. Thank you for the note!
